# Generated by Django 4.1.2 on 2022-11-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_room', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to='rooms/image1/')),
                ('image2', models.ImageField(upload_to='rooms/image2/')),
                ('image3', models.ImageField(upload_to='rooms/image3/')),
                ('image4', models.ImageField(upload_to='rooms/image4/')),
                ('floor', models.IntegerField(default=1)),
                ('room_number', models.CharField(max_length=10)),
                ('single_beds', models.IntegerField(default=0)),
                ('double_beds', models.IntegerField(default=0)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('iron', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('TV', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('busy', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_room.typeroom')),
            ],
            options={
                'db_table': 'room',
                'ordering': ['name'],
            },
        ),
    ]
