# Generated by Django 4.1.2 on 2022-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='services/')),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['name'],
            },
        ),
    ]
